name: Submit code to the Kaggle competition

on:
  push:
  workflow_dispatch:
  

jobs:
  kaggle-submitter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Kaggle
        uses: osbm/kaggle-login
        with:
          KAGGLE_USERNAME: {{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: {{ secrets.KAGGLE_KEY }}

      - name: Pull Competition Data
        run: |
          mkdir -p data
          cd data
          kaggle competitions download -c santander-customer-transaction-prediction
          unzip santander-customer-transaction-prediction.zip

      - name: Run the code
        run: |
          python preprocess_transactions_sale.py
          python preprocessing.py
          python model.py

      - name: Submit to Kaggle
        run: |
          kaggle competitions submit -c santander-customer-transaction-prediction -f submission.csv -m "Auto submit from GitHub Actions current branch: $GITHUB_REF commit hash: $GITHUB_SHA"

      - name: Get the score from Kaggle
        run: |
          python .github/scripts/get_kaggle_score.py
          
      - name: Make a tag including the score
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a ${{ env.KAGGLE_SCORE }} -m "Auto tag from GitHub Actions current branch: $GITHUB_REF commit hash: $GITHUB_SHA"
          git push --tags


